commands:
  cmd:
    help: "Manage Git operations"
    color: "CYAN"  # 使用合法的 Colorama 颜色名称
    subcommands:
      fetch:
        help: "Fetch all branches from the remote repository"
        color: "YELLOW"  # 使用合法的 Colorama 颜色名称
        type: "system"  # 类型为系统命令
        script: "git fetch --all"
  python:
    help: "Run a custom Python script"
    color: "MAGENTA"  # 使用合法的 Colorama 颜色名称
    subcommands:
      hello:
        help: "Run a custom Python script"
        color: "WHITE"  # 使用合法的 Colorama 颜色名称
        type: "python"  # 类型为Python脚本
        script: "ws/python_script/python_example.py"
  bash:
    help: "Run a custom Bash script"
    color: "RED"  # 使用合法的 Colorama 颜色名称
    subcommands:
      hello:
        help: "Run a custom Bash script"
        color: "YELLOW"  # 使用合法的 Colorama 颜色名称
        type: "bash"  # 类型为Bash脚本
        script: "ws/bash/bash_example.sh"
  exec:
    help: "Run a custom binary executable"
    color: "CYAN"  # 使用合法的 Colorama 颜色名称
    subcommands:
      hello:
        help: "Run a custom binary executable"
        color: "GREEN"  # 使用合法的 Colorama 颜色名称
        type: "binary"  # 类型为二进制可执行程序
        script: "none"

